import { createContext, useContext, useState } from 'react';

const T = {
  fr: {
    storeName: 'Gestion File', liveLabel: 'EN DIRECT',
    tabs: { live: 'En direct', forecast: 'Prévision', today: "Aujourd'hui", alerts: 'Alertes' },
    clients: 'clients',
    liveQueueStatus: 'ÉTAT DES FILES',
    inQueue: 'EN FILE', avgWait: 'ATTENTE MOY.',
    openWord: 'Ouverte', busyWord: 'Chargée', closedWord: 'Fermée',
    liveCameras: 'CAMÉRAS', camEntrance: 'CAM 1 · ENTRÉE', camCheckout: 'CAM 2 · CAISSES',
    inQueueChip: n => `${n} en file`,
    cameraOffline: id => `Cam ${id} hors ligne`,
    serverError: 'Impossible de joindre le serveur.',
    justNow: "À l'instant", secondsAgo: s => `il y a ${s}s`,
    staleData: min => `dernière donnée il y a ${min} min`,
    forecastTitle: 'PRÉVISION',
    recActionTitle: 'Ouvrir une file supplémentaire',
    recHighDemandTitle: 'Forte demande — toutes les files ouvertes',
    recOptimalTitle: 'Conditions optimales',
    whyBreach: (time, arrivals, lanes) => `Dépassement des 5 min prévu vers ${time} · ${arrivals} arrivées prévues sur 15 min · ${lanes}`,
    whyStable: lanes => `Attente sous 5 min · ${lanes}`,
    filesCount: n => `${n} file${n !== 1 ? 's' : ''} ouverte${n !== 1 ? 's' : ''}`,
    thresholdLabel: 'Seuil 5 min',
    currentTag: 'actuel', recommendedTag: 'recommandé',
    estimatedWait: "Temps d'attente estimé",
    forecastChart: "PRÉVISION TEMPS D'ATTENTE", next60min: 'Prochaines 60 minutes',
    laneScenarios: 'FILES',
    simulateScenarios: "Toucher pour ouvrir/fermer une file",
    laneLabel: n => `File ${n}`,
    todayTitle: "AUJOURD'HUI",
    totalClients: 'CLIENTS TOTAL', peakHour: 'HEURE DE POINTE',
    baskets: 'Paniers', carts: 'Chariots',
    entriesByHour: 'ENTRÉES PAR HEURE',
    noHourlyData: 'Aucune donnée horaire disponible',
    dailySummary: 'RÉSUMÉ',
    avgWaitTime: "Attente moyenne",
    lanesUsed: 'Files utilisées', busiestLane: id => `la + chargée : ${id}`,
    alertTime: 'Temps en alerte',
    alerts: 'ALERTES',
    critical: 'CRITIQUE', urgent: 'URGENT', warning: 'ATTENTION',
    noAlerts: 'Aucune alerte active', allGood: 'Tout est sous contrôle',
    alertHistory: 'HISTORIQUE — 7 JOURS', noAlertHistory: 'Aucune alerte sur les 7 derniers jours',
    openBtn: 'OUVRIR', cannotOpen: "Impossible d'ouvrir", falseAlarm: 'Fausse alarme',
    predictedWait: min => `Attente prévue : ${min} min`,
    laneOpenedToast: n => `File ${n} ouverte`, laneClosedToast: n => `File ${n} fermée`,
    responseRecorded: 'Réponse enregistrée',
    vsLastWeek: pct => `${pct > 0 ? '+' : ''}${pct}% vs même jour semaine dernière`,
    pctOfTotal: pct => `${pct}% du total`,
  },
  en: {
    storeName: 'Queue Manager', liveLabel: 'LIVE',
    tabs: { live: 'Live', forecast: 'Forecast', today: 'Today', alerts: 'Alerts' },
    clients: 'clients',
    liveQueueStatus: 'LANE STATUS',
    inQueue: 'IN QUEUE', avgWait: 'AVG WAIT',
    openWord: 'Open', busyWord: 'Busy', closedWord: 'Closed',
    liveCameras: 'CAMERAS', camEntrance: 'CAM 1 · ENTRANCE', camCheckout: 'CAM 2 · CHECKOUT',
    inQueueChip: n => `${n} in queue`,
    cameraOffline: id => `Cam ${id} offline`,
    serverError: 'Cannot reach server.',
    justNow: 'Just now', secondsAgo: s => `${s}s ago`,
    staleData: min => `last data ${min} min ago`,
    forecastTitle: 'FORECAST',
    recActionTitle: 'Open an additional lane',
    recHighDemandTitle: 'High demand — all lanes open',
    recOptimalTitle: 'Optimal conditions',
    whyBreach: (time, arrivals, lanes) => `5-min threshold expected to be breached around ${time} · ${arrivals} arrivals expected in 15 min · ${lanes}`,
    whyStable: lanes => `Wait under 5 min · ${lanes}`,
    filesCount: n => `${n} lane${n !== 1 ? 's' : ''} open`,
    thresholdLabel: '5 min threshold',
    currentTag: 'current', recommendedTag: 'recommended',
    estimatedWait: 'Estimated wait time',
    forecastChart: 'WAIT TIME FORECAST', next60min: 'Next 60 minutes',
    laneScenarios: 'LANES',
    simulateScenarios: 'Tap to open/close a lane',
    laneLabel: n => `Lane ${n}`,
    todayTitle: 'TODAY',
    totalClients: 'TOTAL CLIENTS', peakHour: 'PEAK HOUR',
    baskets: 'Baskets', carts: 'Carts',
    entriesByHour: 'ENTRIES BY HOUR',
    noHourlyData: 'No hourly data available',
    dailySummary: 'SUMMARY',
    avgWaitTime: 'Avg wait',
    lanesUsed: 'Lanes used', busiestLane: id => `busiest: ${id}`,
    alertTime: 'Alert time',
    alerts: 'ALERTS',
    critical: 'CRITICAL', urgent: 'URGENT', warning: 'WARNING',
    noAlerts: 'No active alerts', allGood: 'Everything is under control',
    alertHistory: 'HISTORY — 7 DAYS', noAlertHistory: 'No alerts in the last 7 days',
    openBtn: 'OPEN', cannotOpen: 'Cannot Open', falseAlarm: 'False Alarm',
    predictedWait: min => `Predicted wait: ${min} min`,
    laneOpenedToast: n => `Lane ${n} opened`, laneClosedToast: n => `Lane ${n} closed`,
    responseRecorded: 'Response recorded',
    vsLastWeek: pct => `${pct > 0 ? '+' : ''}${pct}% vs same day last week`,
    pctOfTotal: pct => `${pct}% of total`,
  },
};

const Ctx = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr');
  return (
    <Ctx.Provider value={{ t: T[lang], lang, setLang }}>
      {children}
    </Ctx.Provider>
  );
}

export const useLang = () => useContext(Ctx);
