auth_type: basic
camID: Bosch_Camera_Entrance
pretrained_model: models/yolov9t.onnx
iou_score: 0.3
ip_address: '192.168.169.1:554/?inst=4'
username: service
password: 'Cam10003!'
min_delay: 0.45
min_score: 0.3
model: standard.pt
points:
- - 217
  - 196
- - 448
  - 194
- - 559
  - 376
- - 183
  - 433
face_score: 0.35
