from __future__ import annotations

import os
os.environ.setdefault("TF_ENABLE_ONEDNN_OPTS", "0")

import hashlib
import json
import pickle
import time as _time
from pathlib import Path
import sys
import psycopg2
import pandas as pd
import numpy as np
from prophet import Prophet
from datetime import datetime, timedelta, timezone
import warnings
import xgboost as xgb
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

warnings.filterwarnings('ignore')
tf.get_logger().setLevel('ERROR')

ROOT_DIR = Path(__file__).resolve().parents[2]
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

from dotenv import find_dotenv, load_dotenv  # noqa: E402

load_dotenv(find_dotenv(usecwd=True))

from prediction.core import (  # noqa: E402
    BUCKET_MINUTES,
    DEFAULT_DWELL_MIN,
    DEFAULT_LANES,
    DWELL_MAX_CAP,
    DWELL_MIN_FLOOR,
    FORECAST_STEPS,
    LAG_HOUR_STEPS,
    MAX_QUEUE_PER_LANE,
    MAX_WAIT_MIN,
    MIN_REAL_DAYS_FOR_SIM,
    ROLLING_WINDOW_STEPS,
    SEQUENCE_LEN,
    SHOP_OPEN_TOT,
    SNAPSHOT_MAX_AGE_MIN,
    WAIT_45M_INDEX,
    add_closed_zeros,
    build_sim_history,
    compute_wait_estimates,
    future_open_timestamps,
    get_where_clause,
    is_open,
)
from prediction.pipeline import DB_CONFIG  # noqa: E402

STORE_TZ = os.getenv("STORE_TZ", "Europe/Paris")
CHECKOUT_CAM_ID = os.getenv("CHECKOUT_CAM_ID", "Bosch_Camera_exit")


def _connect():
    """
    psycopg2.connect + SET timezone. Without this, a naive local
    datetime (e.g. "13:48") gets stored as if it were already UTC,
    shifting every prediction_for by the local UTC offset (2h in
    summer) — which silently makes /forecast-chart's "NOW() to +60min"
    window never match the rows this script just wrote.
    """
    conn = psycopg2.connect(**DB_CONFIG)
    with conn.cursor() as cur:
        cur.execute("SET timezone = %s", (STORE_TZ,))
    conn.commit()
    return conn


W_PROPHET           = float(os.getenv("W_PROPHET",          0.40))
W_LSTM              = float(os.getenv("W_LSTM",             0.30))
W_XGB               = float(os.getenv("W_XGB",             0.30))
MODEL_MAX_AGE_HOURS = int(os.getenv("MODEL_MAX_AGE_HOURS",  24))
LSTM_OPENING_BLEND_MAX = float(os.getenv("LSTM_OPENING_BLEND_MAX", 0.85))
LSTM_OPENING_BLEND_MIN = float(os.getenv("LSTM_OPENING_BLEND_MIN", 0.25))
LSTM_OPENING_BLEND_MINUTES = int(os.getenv("LSTM_OPENING_BLEND_MINUTES", 60))
LSTM_OPENING_FLOOR_SHARE_MAX = float(os.getenv("LSTM_OPENING_FLOOR_SHARE_MAX", 0.65))
LSTM_OPENING_FLOOR_SHARE_MIN = float(os.getenv("LSTM_OPENING_FLOOR_SHARE_MIN", 0.20))
SCRIPT_DIR = Path(__file__).resolve().parent
MODELS_DIR = SCRIPT_DIR / "models"
LEGACY_MODEL_DIRS = [Path.cwd() / "models", ROOT_DIR / "models"]
MODELS_DIR.mkdir(exist_ok=True)


def _resolve_model_path(filename: str) -> Path:
    preferred = MODELS_DIR / filename
    if preferred.exists():
        return preferred
    for model_dir in LEGACY_MODEL_DIRS:
        candidate = Path(model_dir) / filename
        if candidate.exists():
            return candidate
    return preferred


LSTM_PATH         = _resolve_model_path(f'lstm_queue_{BUCKET_MINUTES}m.keras')
SCALER_PATH       = _resolve_model_path(f'lstm_scaler_{BUCKET_MINUTES}m.pkl')
XGB_PATH          = _resolve_model_path(f'xgb_queue_{BUCKET_MINUTES}m.json')
PROPHET_PATH      = _resolve_model_path(f'prophet_queue_{BUCKET_MINUTES}m.pkl')
PROPHET_META_PATH = _resolve_model_path(f'prophet_queue_{BUCKET_MINUTES}m_meta.json')
PROPHET_FIT_PATH  = MODELS_DIR / f'prophet_training_fit_{BUCKET_MINUTES}m.csv'
DWELL_MODEL_PATH  = _resolve_model_path(f'xgb_dwell_{BUCKET_MINUTES}m.json')
LSTM_META_PATH    = MODELS_DIR / f'lstm_queue_{BUCKET_MINUTES}m_meta.json'
XGB_META_PATH     = MODELS_DIR / f'xgb_queue_{BUCKET_MINUTES}m_meta.json'
DWELL_META_PATH   = MODELS_DIR / f'xgb_dwell_{BUCKET_MINUTES}m_meta.json'

# Arrival calibration: generated by accuracy_eval.py.
_CALIB_PATH = Path(__file__).parent / "calibration.json"
try:
    _calib = json.loads(_CALIB_PATH.read_text(encoding="utf-8")) if _CALIB_PATH.exists() else {}
except Exception:
    _calib = {}
_k_global = float(_calib.get("k_global", 1.0))
_k_by_hour = {
    int(hour): float(value)
    for hour, value in _calib.get("k_by_hour", {}).items()
}

DWELL_FEATURE_COLS = ["hour", "minute_of_hour", "day_of_week", "is_weekend"]


def _build_lstm_opening_profile(history_df: pd.DataFrame, scaler: MinMaxScaler) -> dict[int, float]:
    """Build a historical opening-hour target in scaled space for early-day LSTM stabilization."""
    if history_df.empty:
        return {}

    opening_end_tot = SHOP_OPEN_TOT + max(BUCKET_MINUTES, LSTM_OPENING_BLEND_MINUTES)
    profile_df = history_df.copy()
    profile_df["ds"] = pd.to_datetime(profile_df["ds"], errors="coerce")
    profile_df["y"] = pd.to_numeric(profile_df["y"], errors="coerce").fillna(0.0)
    profile_df = profile_df.dropna(subset=["ds"])

    if profile_df.empty:
        return {}

    profile_df["minute_of_day"] = profile_df["ds"].dt.hour * 60 + profile_df["ds"].dt.minute
    profile_df = profile_df[
        profile_df["ds"].map(is_open)
        & profile_df["minute_of_day"].between(SHOP_OPEN_TOT, opening_end_tot - 1)
    ]

    if profile_df.empty:
        return {}

    opening_profile = (
        profile_df.groupby("minute_of_day", as_index=True)["y"]
        .median()
        .sort_index()
    )

    scaled_profile = scaler.transform(opening_profile.to_numpy(dtype=float).reshape(-1, 1)).flatten()
    return {
        int(minute_of_day): float(scaled_value)
        for minute_of_day, scaled_value in zip(opening_profile.index.tolist(), scaled_profile.tolist())
    }


def _build_lstm_opening_profile_raw(history_df: pd.DataFrame) -> dict[int, float]:
    """Build a raw-space opening profile for a conservative morning floor."""
    if history_df.empty:
        return {}

    opening_end_tot = SHOP_OPEN_TOT + max(BUCKET_MINUTES, LSTM_OPENING_BLEND_MINUTES)
    profile_df = history_df.copy()
    profile_df["ds"] = pd.to_datetime(profile_df["ds"], errors="coerce")
    profile_df["y"] = pd.to_numeric(profile_df["y"], errors="coerce").fillna(0.0)
    profile_df = profile_df.dropna(subset=["ds"])

    if profile_df.empty:
        return {}

    profile_df["minute_of_day"] = profile_df["ds"].dt.hour * 60 + profile_df["ds"].dt.minute
    profile_df = profile_df[
        profile_df["ds"].map(is_open)
        & profile_df["minute_of_day"].between(SHOP_OPEN_TOT, opening_end_tot - 1)
    ]

    if profile_df.empty:
        return {}

    opening_profile = (
        profile_df.groupby("minute_of_day", as_index=True)["y"]
        .median()
        .sort_index()
    )
    return {int(minute_of_day): float(value) for minute_of_day, value in opening_profile.items()}


def _models_are_fresh() -> bool:
    paths = [LSTM_PATH, SCALER_PATH, XGB_PATH, PROPHET_PATH]
    if not all(os.path.exists(p) for p in paths):
        return False
    oldest = min(os.path.getmtime(p) for p in paths)
    return (_time.time() - oldest) < MODEL_MAX_AGE_HOURS * 3600


def _path_is_fresh(path: Path) -> bool:
    return os.path.exists(path) and (_time.time() - os.path.getmtime(path)) < MODEL_MAX_AGE_HOURS * 3600


def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return {}


def _save_json(path: Path, payload: dict) -> None:
    with open(path, "w") as f:
        json.dump(payload, f, indent=2)


DATA_SPAN_DAYS_DEFAULT = int(os.getenv("DATA_SPAN_DAYS", 30))


def _log(message: str) -> None:
    print(message, flush=True)


def _fmt_ts(value) -> str:
    if value is None or pd.isna(value):
        return "n/a"
    return pd.Timestamp(value).strftime("%Y-%m-%d %H:%M:%S")


def _to_local_wall_series(series: pd.Series) -> pd.Series:
    """Convert DB UTC timestamps into timezone-naive local wall-clock time."""
    utc_offset = datetime.now(timezone.utc).astimezone().utcoffset()
    return pd.to_datetime(series).dt.tz_localize(None) + utc_offset


def _frame_fingerprint(df: pd.DataFrame) -> str:
    """Stable short fingerprint for comparing Prophet training frames between runs."""
    if df.empty:
        return "empty"
    stable = df[["ds", "y"]].copy()
    stable["ds"] = pd.to_datetime(stable["ds"], errors="coerce").dt.strftime("%Y-%m-%d %H:%M:%S")
    stable["y"] = pd.to_numeric(stable["y"], errors="coerce").fillna(0).round(4)
    payload = stable.to_csv(index=False).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()[:16]


def _log_prophet_frame(label: str, frame: pd.DataFrame) -> str:
    if frame.empty:
        _log(f"[Prophet:Data] {label}: EMPTY")
        return "empty"

    dbg = frame[["ds", "y"]].copy()
    dbg["ds"] = pd.to_datetime(dbg["ds"], errors="coerce")
    dbg["y"] = pd.to_numeric(dbg["y"], errors="coerce").fillna(0)
    dbg = dbg.dropna(subset=["ds"]).sort_values("ds").reset_index(drop=True)
    fingerprint = _frame_fingerprint(dbg)
    open_mask = dbg["ds"].map(lambda t: is_open(pd.Timestamp(t)))
    nonzero = dbg[dbg["y"] > 0]
    unique_days = int(dbg["ds"].dt.date.nunique())
    sample_head = ", ".join(
        f"{row.ds.strftime('%m-%d %H:%M')}={row.y:.1f}" for row in dbg.head(4).itertuples()
    )
    sample_tail = ", ".join(
        f"{row.ds.strftime('%m-%d %H:%M')}={row.y:.1f}" for row in dbg.tail(4).itertuples()
    )

    _log(
        f"[Prophet:Data] {label}: rows={len(dbg)} unique_days={unique_days} "
        f"open_rows={int(open_mask.sum())} closed_rows={int((~open_mask).sum())} "
        f"nonzero_rows={len(nonzero)} fingerprint={fingerprint}"
    )
    _log(
        f"[Prophet:Data] {label}: window={_fmt_ts(dbg['ds'].min())} -> {_fmt_ts(dbg['ds'].max())} "
        f"sum={float(dbg['y'].sum()):.2f} mean={float(dbg['y'].mean()):.3f} "
        f"median={float(dbg['y'].median()):.3f} max={float(dbg['y'].max()):.2f}"
    )
    if not nonzero.empty:
        _log(
            f"[Prophet:Data] {label}: nonzero_window={_fmt_ts(nonzero['ds'].min())} -> "
            f"{_fmt_ts(nonzero['ds'].max())}"
        )
    _log(f"[Prophet:Data] {label}: first4 {sample_head}")
    _log(f"[Prophet:Data] {label}: last4 {sample_tail}")
    return fingerprint


def _truthy_env(name: str) -> bool:
    return os.getenv(name, "").strip().lower() in {"1", "true", "yes", "on"}


def run_ensemble_forecast(source: str = "REAL", bootstrap: bool = False, data_span_days: int = DATA_SPAN_DAYS_DEFAULT) -> dict:
    """Train Prophet + LSTM + XGBoost ensemble and return a forecast dict."""
    run_started = datetime.now()
    _log("=" * 90)
    _log(
        "[Run] Ensemble forecast started "
        f"at {run_started.strftime('%Y-%m-%d %H:%M:%S')} | source={source} "
        f"days={data_span_days} bootstrap={bootstrap}"
    )
    _log(
        "[Config] "
        f"bucket={BUCKET_MINUTES}min forecast_steps={FORECAST_STEPS} "
        f"weights prophet={W_PROPHET:.2f} lstm={W_LSTM:.2f} xgb={W_XGB:.2f} "
        f"model_max_age={MODEL_MAX_AGE_HOURS}h"
    )
    _log(
        "[Paths] "
        f"prophet={PROPHET_PATH} | lstm={LSTM_PATH} | xgb={XGB_PATH} | dwell={DWELL_MODEL_PATH}"
    )
    where_clause = get_where_clause(source)

    # ── 1. Load data ─────────────────────────────────────────────────────────
    conn = _connect()
    _log(f"[DB] Connected to PostgreSQL database={DB_CONFIG.get('dbname')} host={DB_CONFIG.get('host')} [ok]")

    clean_filter = f"timestamp >= NOW() - INTERVAL '{data_span_days} days' AND dwell_seconds >= 10"
    if where_clause:
        data_filter = f"{where_clause} AND {clean_filter}"
    else:
        data_filter = f"WHERE {clean_filter}"
    _log(f"[Data] entrance_events filter: {data_filter}")

    query = f"""
        SELECT
            time_bucket('{BUCKET_MINUTES} minutes', timestamp) AS bucket,
            COUNT(*) AS entry_count
        FROM entrance_events
        {data_filter}
        GROUP BY bucket
        ORDER BY bucket
    """
    df_real = pd.read_sql(query, conn)
    conn.close()
    _log(f"[Data] Loaded {len(df_real)} non-empty {BUCKET_MINUTES}-min buckets from DB")

    if len(df_real) > 0:
        df_real["entry_count"] = pd.to_numeric(df_real["entry_count"], errors="coerce").fillna(0).astype(int)
        _log(
            "[Data] Raw bucket window: "
            f"{_fmt_ts(df_real['bucket'].min())} -> {_fmt_ts(df_real['bucket'].max())} | "
            f"total_entries={int(df_real['entry_count'].sum())} "
            f"mean={float(df_real['entry_count'].mean()):.2f} max={int(df_real['entry_count'].max())}"
        )
    else:
        _log("[Data] Raw bucket window: no entrance buckets found for selected filter")

    df_real_r = df_real.rename(columns={"bucket": "ds", "entry_count": "y"})
    df_real_r["ds"] = _to_local_wall_series(df_real_r["ds"])
    df_real_r["y"]  = pd.to_numeric(df_real_r["y"], errors="coerce").fillna(0).astype(int)
    _log("[Prophet:Time] Converted DB bucket timestamps to local wall-clock time before training/export")
    _prophet_raw_fingerprint = _log_prophet_frame("raw DB buckets before smoothing/fill", df_real_r)

    real_span_days = (
        (df_real_r["ds"].max() - df_real_r["ds"].min()).total_seconds() / 86400
        if len(df_real_r) > 1 else 0
    )

    # ── 2. Bootstrap ─────────────────────────────────────────────────────────
    if bootstrap and real_span_days < MIN_REAL_DAYS_FOR_SIM:
        df_sim = build_sim_history(days=7)
        df = (
            pd.concat([df_real_r, df_sim], ignore_index=True)
            .drop_duplicates(subset="ds")
            .sort_values("ds")
            .reset_index(drop=True)
        )
        print(f"[Ensemble] Bootstrap ON — {len(df_real_r)} real + {len(df_sim)} synthetic rows")
    else:
        df = df_real_r.sort_values("ds").reset_index(drop=True)
        if bootstrap and real_span_days >= MIN_REAL_DAYS_FOR_SIM:
            _log(f"[Data] {real_span_days:.2f} days real - bootstrap not needed")
        else:
            _log(f"[Data] {real_span_days:.2f} days real - training on real data only")

    df["ds"] = pd.to_datetime(df["ds"], errors="coerce")
    df["y"]  = pd.to_numeric(df["y"], errors="coerce").fillna(0)
    df = df.dropna(subset=["ds"])

    if df.empty:
        raise RuntimeError("No valid data to train. Check --source filter or DB contents.")

    # ── 3. Outlier cap ───────────────────────────────────────────────────────
    non_zero = df.loc[df["y"] > 0, "y"]
    if not non_zero.empty:
        cap_value = max(float(non_zero.quantile(0.99)), 30.0)
        df["y"] = df["y"].clip(upper=cap_value)
        _log(f"[Data] Outlier cap applied at y<={cap_value:.2f} from {len(non_zero)} non-zero buckets")
    else:
        _log("[Data] No non-zero buckets before closed-hour fill")

    # ── 3b. 15-min rolling median smooth (5 × 3-min buckets) ─────────────────
    df["y"] = (
        df["y"]
        .rolling(window=5, center=True, min_periods=1)
        .median()
        .round(2)
    )
    _log("[Data] Applied 15-min rolling median smooth to training data")

    # ── 4. Closed-hour zeros ─────────────────────────────────────────────────
    df = add_closed_zeros(df[["ds", "y"]].copy(), days=data_span_days)

    _open_mask_train = df["ds"].map(lambda t: is_open(pd.Timestamp(t)))
    _log(
        "[Data] Final Prophet/LSTM/XGB frame: "
        f"rows={len(df)} open_rows={int(_open_mask_train.sum())} closed_zero_rows={int((~_open_mask_train).sum())} "
        f"window={_fmt_ts(df['ds'].min())} -> {_fmt_ts(df['ds'].max())} "
        f"total_y={float(df['y'].sum()):.1f} mean_y={float(df['y'].mean()):.2f} max_y={float(df['y'].max()):.1f}"
    )
    _prophet_train_fingerprint = _log_prophet_frame("final training frame after smoothing/fill", df)

    future_timestamps = future_open_timestamps()
    future_df = pd.DataFrame({"ds": future_timestamps})
    n_steps = len(future_timestamps)
    _log(
        "[Future] "
        f"steps={n_steps} window={_fmt_ts(future_df['ds'].min() if not future_df.empty else None)} "
        f"-> {_fmt_ts(future_df['ds'].max() if not future_df.empty else None)}"
    )

    # ── MODEL 1 — PROPHET ────────────────────────────────────────────────────
    _prophet_meta = {}
    if os.path.exists(PROPHET_META_PATH):
        try:
            with open(PROPHET_META_PATH) as _mf:
                _prophet_meta = json.load(_mf)
        except Exception:
            _prophet_meta = {}
    _prophet_days_changed = _prophet_meta.get("data_span_days") != data_span_days
    _prophet_data_changed = _prophet_meta.get("train_fingerprint") != _prophet_train_fingerprint
    _force_prophet_retrain = _truthy_env("FORCE_PROPHET_RETRAIN")
    _models_fresh = _models_are_fresh()
    _log(
        "[Prophet:Cache] "
        f"all_core_models_fresh={_models_fresh} "
        f"prophet_meta_days={_prophet_meta.get('data_span_days', 'none')} "
        f"requested_days={data_span_days} prophet_days_changed={_prophet_days_changed} "
        f"meta_fingerprint={_prophet_meta.get('train_fingerprint', 'none')} "
        f"current_fingerprint={_prophet_train_fingerprint} "
        f"prophet_data_changed={_prophet_data_changed} force={_force_prophet_retrain}"
    )

    _prophet_cache_ok = (
        _models_fresh
        and not _prophet_days_changed
        and not _prophet_data_changed
        and not _force_prophet_retrain
    )
    if _prophet_cache_ok:
        _log("\n[Prophet] Loading saved model...")
        with open(PROPHET_PATH, "rb") as _f:
            prophet_model = pickle.load(_f)
        _log("[Prophet] Loaded [ok]")
    else:
        _reasons = []
        if _prophet_days_changed:
            _reasons.append("days changed")
        if _prophet_data_changed:
            _reasons.append("data changed")
        if _force_prophet_retrain:
            _reasons.append("FORCE_PROPHET_RETRAIN")
        if not _models_fresh:
            _reasons.append("model stale/missing")
        _reason = ", ".join(_reasons) if _reasons else "cache disabled"
        _cps = 0.30 if data_span_days <= 10 else (0.15 if data_span_days <= 20 else 0.1)
        _prophet_params = {
            "daily_seasonality": False,
            "weekly_seasonality": data_span_days >= 7,
            "yearly_seasonality": False,
            "changepoint_prior_scale": _cps,
            "seasonality_prior_scale": 10.0,
            "interval_width": 0.80,
            "daily_fourier_order": 10,
            "weekly_fourier_order": 5 if data_span_days >= 7 else 0,
        }
        _log(
            f"\n[Prophet] Training ({_reason}, span={data_span_days}d) | "
            f"rows={len(df)} train_fingerprint={_prophet_train_fingerprint}"
        )
        _log(f"[Prophet:Params] {json.dumps(_prophet_params, sort_keys=True)}")
        prophet_model = Prophet(
            daily_seasonality=False,   # replaced by custom higher-order below
            weekly_seasonality=(data_span_days >= 7),
            yearly_seasonality=False,
            changepoint_prior_scale=_cps,
            seasonality_prior_scale=10.0,
            interval_width=0.80,
        )
        # Higher Fourier order → captures sharp morning/lunch/evening transitions
        prophet_model.add_seasonality(name='daily',  period=1,   fourier_order=10)
        if data_span_days >= 7:
            prophet_model.add_seasonality(name='weekly', period=7, fourier_order=5)
        prophet_model.fit(df)
        with open(PROPHET_PATH, "wb") as _f:
            pickle.dump(prophet_model, _f)
        with open(PROPHET_META_PATH, "w") as _mf:
            json.dump(
                {
                    "data_span_days": data_span_days,
                    "raw_fingerprint": _prophet_raw_fingerprint,
                    "train_fingerprint": _prophet_train_fingerprint,
                    "train_rows": int(len(df)),
                    "train_start": _fmt_ts(df["ds"].min()),
                    "train_end": _fmt_ts(df["ds"].max()),
                    "train_y_sum": float(df["y"].sum()),
                    "params": _prophet_params,
                    "saved_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                },
                _mf,
                indent=2,
            )
        _log("[Prophet] Trained and saved [ok]")
    prophet_train_fit = prophet_model.predict(df[["ds"]])[["ds", "yhat", "yhat_lower", "yhat_upper"]]
    prophet_train_fit = df[["ds", "y"]].merge(prophet_train_fit, on="ds", how="left")
    prophet_train_fit["data_span_days"] = data_span_days
    prophet_train_fit["train_fingerprint"] = _prophet_train_fingerprint
    prophet_train_fit.to_csv(PROPHET_FIT_PATH, index=False)
    _log(f"[Prophet] Saved training fit curve to {PROPHET_FIT_PATH}")
    forecast       = prophet_model.predict(future_df)
    prophet_preds  = forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]].reset_index(drop=True)
    prophet_vals   = prophet_preds["yhat"].clip(lower=0).values
    _log(
        "[Prophet] Forecast summary: "
        f"min={float(np.min(prophet_vals)):.2f} mean={float(np.mean(prophet_vals)):.2f} "
        f"max={float(np.max(prophet_vals)):.2f}"
    )
    _prophet_preview = ", ".join(
        f"{row.ds.strftime('%H:%M')}={row.yhat:.2f}" for row in prophet_preds.head(6).itertuples()
    )
    _log(f"[Prophet] Forecast first6: {_prophet_preview}")

    # ── MODEL 2 — LSTM ───────────────────────────────────────────────────────
    _log("\n[LSTM] Preparing sequences...")

    def _make_sequences(data, seq_len):
        X, y_out = [], []
        for i in range(len(data) - seq_len):
            X.append(data[i: i + seq_len])
            y_out.append(data[i + seq_len])
        return np.array(X), np.array(y_out)

    y_values = pd.to_numeric(df["y"], errors="coerce").fillna(0).values
    y_values = np.nan_to_num(y_values, nan=0.0, posinf=0.0, neginf=0.0)

    # Use open-hours-only data for LSTM training and seed.
    # Closed-hour zeros contaminate the sequence window and cause the model to
    # predict near-zero when it runs outside shop hours (zero-seed problem).
    _open_mask_lstm = np.array([is_open(pd.Timestamp(t)) for t in df["ds"].values])
    y_open_values   = y_values[_open_mask_lstm]

    _log(f"[LSTM] open_values={len(y_open_values)} sequence_len={SEQUENCE_LEN}")
    _lstm_meta = _load_json(LSTM_META_PATH)
    _lstm_cache_ok = (
        _path_is_fresh(LSTM_PATH)
        and _path_is_fresh(SCALER_PATH)
        and _lstm_meta.get("data_span_days") == data_span_days
        and _lstm_meta.get("train_fingerprint") == _prophet_train_fingerprint
        and not _truthy_env("FORCE_LSTM_RETRAIN")
    )
    _log(
        "[LSTM:Cache] "
        f"fresh={_path_is_fresh(LSTM_PATH) and _path_is_fresh(SCALER_PATH)} "
        f"meta_days={_lstm_meta.get('data_span_days', 'none')} requested_days={data_span_days} "
        f"meta_fingerprint={_lstm_meta.get('train_fingerprint', 'none')} "
        f"current_fingerprint={_prophet_train_fingerprint} cache_ok={_lstm_cache_ok}"
    )

    if _lstm_cache_ok:
        _log("[LSTM] Loading saved model and scaler...")
        lstm_model = tf.keras.models.load_model(LSTM_PATH)
        with open(SCALER_PATH, "rb") as _f:
            scaler = pickle.load(_f)
        y_open_scaled = scaler.transform(y_open_values.reshape(-1, 1))
        _lstm_has_enough_data = True  # a cached model implies a prior run had enough data
        _log("[LSTM] Loaded [ok]")
    else:
        scaler = MinMaxScaler(feature_range=(0, 1))
        if len(df_real_r) > 0:
            real_y_all  = pd.to_numeric(df_real_r["y"], errors="coerce").fillna(0).values
            _real_open  = np.array([is_open(pd.Timestamp(t)) for t in df_real_r["ds"].values])
            real_y_open = real_y_all[_real_open]
            scaler.fit((real_y_open if len(real_y_open) > 0 else real_y_all).reshape(-1, 1))
        else:
            scaler.fit(y_open_values.reshape(-1, 1))
        y_open_scaled = scaler.transform(y_open_values.reshape(-1, 1))

        X_lstm, y_lstm = _make_sequences(y_open_scaled, SEQUENCE_LEN)
        _lstm_has_enough_data = len(X_lstm) > 0
        _log(f"[LSTM] Training on {len(X_lstm)} open-hour sequences (epochs=20)...")
        lstm_model = Sequential([
            LSTM(64, input_shape=(SEQUENCE_LEN, 1), return_sequences=True),
            Dropout(0.2),
            LSTM(32),
            Dropout(0.2),
            Dense(1),
        ])
        lstm_model.compile(optimizer="adam", loss="mse")
        if _lstm_has_enough_data:
            lstm_model.fit(X_lstm, y_lstm, epochs=20, batch_size=32, verbose=0)
            lstm_model.save(LSTM_PATH)
            with open(SCALER_PATH, "wb") as _f:
                pickle.dump(scaler, _f)
            _save_json(LSTM_META_PATH, {
                "data_span_days": data_span_days,
                "train_fingerprint": _prophet_train_fingerprint,
                "open_values": int(len(y_open_values)),
                "saved_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            })
            _log("[LSTM] Trained and saved [ok]")
        else:
            _log(
                f"[LSTM] Skipping training — only {len(y_open_values)} open-hour value(s) "
                f"available, need at least {SEQUENCE_LEN} for one sequence. Falling back to "
                "a naive flat forecast for this run instead of crashing the whole ensemble "
                "(Prophet + XGBoost still run normally)."
            )

    opening_profile_source = df_real_r if len(df_real_r) > 0 else df[["ds", "y"]]
    opening_profile_scaled = _build_lstm_opening_profile(opening_profile_source, scaler)
    opening_profile_raw = _build_lstm_opening_profile_raw(opening_profile_source)
    if opening_profile_scaled:
        _log(
            "[LSTM] Built opening profile "
            f"({len(opening_profile_scaled)} buckets over first {LSTM_OPENING_BLEND_MINUTES} min)"
        )

    # Seed from the last SEQUENCE_LEN open-hour values — not the raw tail
    # which may end in overnight zeros and cause near-zero rollout predictions.
    if _lstm_has_enough_data:
        last_seq = y_open_scaled[-SEQUENCE_LEN:].copy() if len(y_open_scaled) >= SEQUENCE_LEN \
                   else y_open_scaled.copy()
        lstm_scaled_preds = []
        opening_span = max(BUCKET_MINUTES, LSTM_OPENING_BLEND_MINUTES)
        opening_fade_span = max(1, opening_span - BUCKET_MINUTES)
        for ts in future_timestamps:
            inp      = last_seq.reshape(1, SEQUENCE_LEN, 1)
            next_val = lstm_model.predict(inp, verbose=0)[0][0]
            ts_dt = pd.Timestamp(ts)
            minute_of_day = ts_dt.hour * 60 + ts_dt.minute
            opening_target = opening_profile_scaled.get(minute_of_day)
            if opening_target is not None and SHOP_OPEN_TOT <= minute_of_day < (SHOP_OPEN_TOT + opening_span):
                progress = min(1.0, max(0.0, (minute_of_day - SHOP_OPEN_TOT) / opening_fade_span))
                blend_weight = LSTM_OPENING_BLEND_MAX + (
                    (LSTM_OPENING_BLEND_MIN - LSTM_OPENING_BLEND_MAX) * progress
                )
                next_val = ((1.0 - blend_weight) * float(next_val)) + (blend_weight * opening_target)
            lstm_scaled_preds.append(next_val)
            last_seq = np.append(last_seq[1:], [[next_val]], axis=0)

        lstm_vals = scaler.inverse_transform(
            np.array(lstm_scaled_preds).reshape(-1, 1)
        ).flatten().clip(min=0)
    else:
        # Not enough open-hour history to seed a real sequence (reshaping a
        # too-short window to (1, SEQUENCE_LEN, 1) is what used to crash here).
        # Naive fallback: repeat the mean of whatever real values exist, so
        # Prophet + XGBoost can still carry the ensemble for this run.
        _naive_scaled = float(np.mean(y_open_scaled)) if len(y_open_scaled) > 0 else 0.5
        lstm_vals = np.full(len(future_timestamps), _naive_scaled, dtype=float)
        lstm_vals = scaler.inverse_transform(
            lstm_vals.reshape(-1, 1)
        ).flatten().clip(min=0)
        _log(f"[LSTM] Using naive flat fallback ({len(future_timestamps)} steps) — insufficient data for real rollout")

    # ── MODEL 3 — XGBOOST ───────────────────────────────────────────────────
    _log("\n[XGBoost] Building features...")

    FEATURE_COLS = [
        "hour", "minute_of_hour", "day_of_week", "is_weekend",
        "lag_1", "lag_2", "lag_3", "lag_12", "rolling_mean_6",
    ]

    def _build_features(data_df):
        d = data_df.copy()
        d["hour"]           = d["ds"].dt.hour
        d["minute_of_hour"] = d["ds"].dt.minute
        d["day_of_week"]    = d["ds"].dt.dayofweek
        d["is_weekend"]     = (d["day_of_week"] >= 5).astype(int)
        d["lag_1"]          = d["y"].shift(1)
        d["lag_2"]          = d["y"].shift(2)
        d["lag_3"]          = d["y"].shift(3)
        d["lag_12"]         = d["y"].shift(LAG_HOUR_STEPS)
        d["rolling_mean_6"] = d["y"].shift(1).rolling(ROLLING_WINDOW_STEPS).mean()
        return d.dropna()

    df_feat = _build_features(df)
    _log(f"[XGBoost] Feature rows={len(df_feat)} feature_cols={FEATURE_COLS}")
    _xgb_meta = _load_json(XGB_META_PATH)
    _xgb_cache_ok = (
        _path_is_fresh(XGB_PATH)
        and _xgb_meta.get("data_span_days") == data_span_days
        and _xgb_meta.get("train_fingerprint") == _prophet_train_fingerprint
        and not _truthy_env("FORCE_XGB_RETRAIN")
    )
    _log(
        "[XGBoost:Cache] "
        f"fresh={_path_is_fresh(XGB_PATH)} "
        f"meta_days={_xgb_meta.get('data_span_days', 'none')} requested_days={data_span_days} "
        f"meta_fingerprint={_xgb_meta.get('train_fingerprint', 'none')} "
        f"current_fingerprint={_prophet_train_fingerprint} cache_ok={_xgb_cache_ok}"
    )

    if _xgb_cache_ok:
        _log("[XGBoost] Loading saved model...")
        xgb_model = xgb.XGBRegressor()
        xgb_model.load_model(XGB_PATH)
        _log("[XGBoost] Loaded [ok]")
    else:
        xgb_model = xgb.XGBRegressor(
            n_estimators=200, max_depth=4, learning_rate=0.05,
            subsample=0.8, colsample_bytree=0.8, random_state=42, verbosity=0,
        )
        xgb_model.fit(df_feat[FEATURE_COLS], df_feat["y"])
        xgb_model.save_model(XGB_PATH)
        _save_json(XGB_META_PATH, {
            "data_span_days": data_span_days,
            "train_fingerprint": _prophet_train_fingerprint,
            "feature_rows": int(len(df_feat)),
            "saved_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        })
        _log("[XGBoost] Trained and saved [ok]")

    # Seed from real observed data only — df["y"] ends with add_closed_zeros synthetic
    # zeros for overnight/post-close gaps, which poison lag_1/lag_2/lag_3 and
    # rolling_mean at the opening of each day and cause near-zero predictions.
    _real_seed = df_real_r.sort_values("ds").reset_index(drop=True)
    recent_y = _real_seed["y"].tolist() if len(_real_seed) > 0 else df["y"].tolist()
    xgb_vals = []
    for ts in future_timestamps:
        ts_dt = pd.Timestamp(ts)
        row = {
            "hour":           ts_dt.hour,
            "minute_of_hour": ts_dt.minute,
            "day_of_week":    ts_dt.dayofweek,
            "is_weekend":     int(ts_dt.dayofweek >= 5),
            "lag_1":          recent_y[-1],
            "lag_2":          recent_y[-2] if len(recent_y) >= 2 else recent_y[-1],
            "lag_3":          recent_y[-3] if len(recent_y) >= 3 else recent_y[-1],
            "lag_12":         recent_y[-LAG_HOUR_STEPS] if len(recent_y) >= LAG_HOUR_STEPS else recent_y[0],
            "rolling_mean_6": np.mean(recent_y[-ROLLING_WINDOW_STEPS:]) if len(recent_y) >= ROLLING_WINDOW_STEPS else np.mean(recent_y),
        }
        pred = max(0.0, float(xgb_model.predict(pd.DataFrame([row]))[0]))
        xgb_vals.append(pred)
        recent_y.append(pred)
    xgb_vals = np.array(xgb_vals)

    # Apply a conservative first-hour opening floor so the LSTM does not stay at
    # the previous evening's low regime when Prophet/XGBoost already indicate demand.
    for i, ts in enumerate(future_timestamps):
        ts_dt = pd.Timestamp(ts)
        minute_of_day = ts_dt.hour * 60 + ts_dt.minute
        if not (SHOP_OPEN_TOT <= minute_of_day < (SHOP_OPEN_TOT + opening_span)):
            continue

        progress = min(1.0, max(0.0, (minute_of_day - SHOP_OPEN_TOT) / opening_fade_span))
        floor_share = LSTM_OPENING_FLOOR_SHARE_MAX + (
            (LSTM_OPENING_FLOOR_SHARE_MIN - LSTM_OPENING_FLOOR_SHARE_MAX) * progress
        )
        opening_hist = float(opening_profile_raw.get(minute_of_day, 0.0))
        # XGBoost floor: use Prophet as baseline (XGBoost may still be low from stale lags)
        xgb_baseline = max(opening_hist, 0.6 * float(prophet_vals[i]))
        xgb_floor = max(0.0, floor_share * xgb_baseline)
        xgb_vals[i] = max(float(xgb_vals[i]), xgb_floor)
        # LSTM floor: use the now-corrected XGBoost alongside Prophet
        model_baseline = max(float(prophet_vals[i]), float(xgb_vals[i]))
        opening_baseline = max(opening_hist, 0.6 * model_baseline)
        morning_floor = max(0.0, floor_share * opening_baseline)
        lstm_vals[i] = max(float(lstm_vals[i]), morning_floor)

    # ── ENSEMBLE ─────────────────────────────────────────────────────────────
    _log("\n[Ensemble] Combining predictions (Prophet 40% / LSTM 30% / XGBoost 30%)...")
    ensemble_vals_raw = (W_PROPHET * prophet_vals + W_LSTM * lstm_vals + W_XGB * xgb_vals).clip(min=0)
    ensemble_vals = ensemble_vals_raw.copy()
    if _k_by_hour or abs(_k_global - 1.0) > 1e-9:
        _log(
            "[Calibration] Applying ensemble arrival calibration "
            f"(k_global={_k_global:.4f}, hourly_slots={len(_k_by_hour)})"
        )
        for i, ts in enumerate(future_timestamps):
            hour = pd.Timestamp(ts).hour
            k = _k_by_hour.get(hour, _k_global)
            ensemble_vals[i] = max(0.0, float(ensemble_vals[i]) * k)
    ensemble_vals = ensemble_vals.round(1)
    _log(
        "[Ensemble] Forecast summary: "
        f"prophet_mean={float(np.mean(prophet_vals)):.2f} "
        f"lstm_mean={float(np.mean(lstm_vals)):.2f} "
        f"xgb_mean={float(np.mean(xgb_vals)):.2f} "
        f"ensemble_mean={float(np.mean(ensemble_vals)):.2f}"
    )

    # ── Wait estimates ────────────────────────────────────────────────────────
    # Scoped to the actual checkout camera only — MAX(active_lanes)/SUM(queue_count)
    # across every camera_id ever recorded was picking up months-stale rows from
    # unrelated/renamed cameras (including a case-duplicate "Bosch_Camera_Exit"
    # vs "Bosch_Camera_exit"), inflating the lane count the wait model assumes.
    _log("\n[Wait] Loading current queue state from snapshots...")
    _conn_snap = _connect()
    try:
        snap_latest = pd.read_sql("""
            SELECT NOW() AS timestamp,
                   COALESCE(queue_count, 0) AS queue_count,
                   active_lanes
            FROM queue_state_snapshots
            WHERE camera_id = %(cam)s
            ORDER BY timestamp DESC
            LIMIT 1
        """, _conn_snap, params={"cam": CHECKOUT_CAM_ID})
    finally:
        _conn_snap.close()

    snap_age_min = None
    if len(snap_latest) > 0:
        snap_ts = pd.Timestamp(snap_latest.iloc[0]["timestamp"])
        if snap_ts.tzinfo is not None:
            snap_age_min = (pd.Timestamp.now(tz="UTC") - snap_ts.tz_convert("UTC")).total_seconds() / 60.0
        else:
            snap_age_min = (pd.Timestamp.now(tz="UTC").tz_localize(None) - snap_ts).total_seconds() / 60.0

    # ── Dwell model: XGBoost on service_events → per-bucket prediction ────────
    print("\n[Dwell] Loading service events for dwell model...")
    _conn_svc = _connect()
    try:
        df_svc = pd.read_sql(f"""
            SELECT timestamp, total_dwell_sec / 60.0 AS service_min
            FROM service_events
            WHERE total_dwell_sec >= {DWELL_MIN_FLOOR * 60}
              AND total_dwell_sec <= {DWELL_MAX_CAP * 60}
              AND timestamp >= NOW() - INTERVAL '{data_span_days} days'
        """, _conn_svc)
    finally:
        _conn_svc.close()
    if not df_svc.empty:
        df_svc["timestamp"] = _to_local_wall_series(df_svc["timestamp"])
        _log(
            "[Dwell:Time] Converted service_event timestamps to local wall-clock time "
            "before dwell model features"
        )

    # Flat median fallback (always compute as safety net)
    svc_median = None
    if not df_svc.empty:
        svc_vals = pd.to_numeric(df_svc["service_min"], errors="coerce").dropna()
        if not svc_vals.empty:
            svc_median = float(svc_vals.median())
    avg_dwell_min = float(np.clip(svc_median, DWELL_MIN_FLOOR, DWELL_MAX_CAP)) if svc_median else float(os.getenv("CHECKOUT_SERVICE_MIN", DEFAULT_DWELL_MIN))

    # Train / load XGBoost dwell model
    dwell_model = None
    _dwell_fingerprint = _frame_fingerprint(
        df_svc.rename(columns={"timestamp": "ds", "service_min": "y"})[["ds", "y"]]
    ) if not df_svc.empty else "empty"
    _dwell_meta = _load_json(DWELL_META_PATH)
    _dwell_cache_ok = (
        _path_is_fresh(DWELL_MODEL_PATH)
        and _dwell_meta.get("data_span_days") == data_span_days
        and _dwell_meta.get("dwell_fingerprint") == _dwell_fingerprint
        and not _truthy_env("FORCE_DWELL_RETRAIN")
    )
    _log(
        "[Dwell:Cache] "
        f"fresh={_path_is_fresh(DWELL_MODEL_PATH)} "
        f"meta_days={_dwell_meta.get('data_span_days', 'none')} requested_days={data_span_days} "
        f"meta_fingerprint={_dwell_meta.get('dwell_fingerprint', 'none')} "
        f"current_fingerprint={_dwell_fingerprint} cache_ok={_dwell_cache_ok}"
    )
    if _dwell_cache_ok:
        print("[Dwell] Loading saved dwell model...")
        dwell_model = xgb.XGBRegressor()
        dwell_model.load_model(DWELL_MODEL_PATH)
        print("[Dwell] Loaded [ok]")
    elif not df_svc.empty and len(df_svc) >= 30:
        print(f"[Dwell] Training dwell model on {len(df_svc)} service events...")
        _ds = df_svc.copy()
        _ds["timestamp"] = pd.to_datetime(_ds["timestamp"])
        _ds["hour"]           = _ds["timestamp"].dt.hour
        _ds["minute_of_hour"] = _ds["timestamp"].dt.minute
        _ds["day_of_week"]    = _ds["timestamp"].dt.dayofweek
        _ds["is_weekend"]     = (_ds["day_of_week"] >= 5).astype(int)
        _ds["service_min"]    = _ds["service_min"].clip(DWELL_MIN_FLOOR, DWELL_MAX_CAP)
        dwell_model = xgb.XGBRegressor(
            n_estimators=300, max_depth=4, learning_rate=0.05,
            subsample=0.8, colsample_bytree=0.8, random_state=42, verbosity=0,
        )
        dwell_model.fit(_ds[DWELL_FEATURE_COLS], _ds["service_min"])
        dwell_model.save_model(DWELL_MODEL_PATH)
        _save_json(DWELL_META_PATH, {
            "data_span_days": data_span_days,
            "dwell_fingerprint": _dwell_fingerprint,
            "events": int(len(df_svc)),
            "saved_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        })
        print(f"[Dwell] Trained and saved [ok]  (median={avg_dwell_min:.2f} min)")
    else:
        print(f"[Dwell] Not enough data ({len(df_svc)} events) — using flat median fallback ({avg_dwell_min:.2f} min)")

    # Per-bucket dwell predictions for future timestamps
    if dwell_model is not None:
        _dwell_rows = [{"hour": pd.Timestamp(ts).hour, "minute_of_hour": pd.Timestamp(ts).minute,
                        "day_of_week": pd.Timestamp(ts).dayofweek, "is_weekend": int(pd.Timestamp(ts).dayofweek >= 5)}
                       for ts in future_timestamps]
        _dwell_raw = dwell_model.predict(pd.DataFrame(_dwell_rows))
        per_bucket_dwell = np.clip(_dwell_raw, DWELL_MIN_FLOOR, DWELL_MAX_CAP).tolist()
        print(f"[Dwell] Per-bucket predictions — min={min(per_bucket_dwell):.2f} max={max(per_bucket_dwell):.2f} mean={np.mean(per_bucket_dwell):.2f} min")
    else:
        per_bucket_dwell = avg_dwell_min  # scalar fallback

    if len(snap_latest) > 0 and (snap_age_min is None or snap_age_min < SNAPSHOT_MAX_AGE_MIN):
        _raw_queue    = int(snap_latest.iloc[0]["queue_count"])
        active_lanes  = max(1, int(snap_latest.iloc[0]["active_lanes"] or DEFAULT_LANES))
        current_queue = max(0, _raw_queue - active_lanes)
        print(f"[Wait] raw_queue={_raw_queue}, in_service={active_lanes}, waiting={current_queue}, service={avg_dwell_min:.1f}min/customer, lanes={active_lanes}")
    else:
        current_queue = 0
        active_lanes  = DEFAULT_LANES
        print("[Wait] No snapshot — using defaults")

    # ── Browsing-gap shift ────────────────────────────────────────────────────
    # A customer who enters the store at time T reaches checkout at T + gap.
    # So checkout arrivals at future step i = entrance arrivals from (i - lag) steps ago.
    # For the initial `lag` steps, we pull actual recent entrance counts from DB.
    BROWSING_GAP_MIN = int(os.getenv("BROWSING_GAP_MIN", 25))
    browsing_lag_steps = max(1, round(BROWSING_GAP_MIN / BUCKET_MINUTES))
    print(f"[Wait] Browsing gap = {BROWSING_GAP_MIN} min ({browsing_lag_steps} buckets) — shifting entrance → checkout...")

    _conn_hist = _connect()
    try:
        df_hist = pd.read_sql(f"""
            SELECT
                time_bucket('{BUCKET_MINUTES} minutes', timestamp) AS bucket,
                COUNT(*) AS entry_count
            FROM entrance_events
            WHERE timestamp >= NOW() - INTERVAL '{BROWSING_GAP_MIN + BUCKET_MINUTES} minutes'
            GROUP BY bucket
            ORDER BY bucket ASC
        """, _conn_hist)
    finally:
        _conn_hist.close()

    df_hist["bucket"] = _to_local_wall_series(df_hist["bucket"])
    hist_by_time = dict(
        zip(df_hist["bucket"].dt.floor(f"{BUCKET_MINUTES}min"),
            df_hist["entry_count"].astype(float))
    )

    checkout_arrivals = np.zeros(n_steps)
    now_floored = pd.Timestamp.now().replace(second=0, microsecond=0,
                  minute=(pd.Timestamp.now().minute // BUCKET_MINUTES) * BUCKET_MINUTES)
    for i in range(n_steps):
        entrance_idx = i - browsing_lag_steps
        if entrance_idx < 0:
            entrance_time = now_floored + pd.Timedelta(minutes=BUCKET_MINUTES * entrance_idx)
            checkout_arrivals[i] = hist_by_time.get(entrance_time, 0.0)
        else:
            checkout_arrivals[i] = ensemble_vals[entrance_idx]

    wait_frame = prophet_preds[["ds"]].copy()
    wait_frame["yhat"] = checkout_arrivals

    wait_rows, wait_15m, wait_30m, service_per_bucket = compute_wait_estimates(
        wait_frame,
        current_queue=current_queue,
        avg_dwell_min=per_bucket_dwell,
        active_lanes=active_lanes,
        max_queue_per_lane=MAX_QUEUE_PER_LANE,
        max_wait_min=MAX_WAIT_MIN,
    )
    wait_estimates = [float(r["wait_min"]) for r in wait_rows]

    # 45-minute horizon
    wait_45m = float(wait_rows[WAIT_45M_INDEX]["wait_min"]) if len(wait_rows) > WAIT_45M_INDEX else wait_30m

    # Lane scenario comparisons — wait at +15 min for 1, 2, 3 lanes
    lane_waits_15m: dict[int, float] = {}
    for n_lanes in [1, 2, 3]:
        _rows, _w15, _, _ = compute_wait_estimates(
            wait_frame,
            current_queue=current_queue,
            avg_dwell_min=per_bucket_dwell,
            active_lanes=n_lanes,
            max_queue_per_lane=MAX_QUEUE_PER_LANE,
            max_wait_min=MAX_WAIT_MIN,
        )
        lane_waits_15m[n_lanes] = float(_w15) if _w15 is not None else 0.0
    print(f"[Wait] Lane scenarios @ +15m — 1 lane: {lane_waits_15m[1]:.1f} min | "
          f"2 lanes: {lane_waits_15m[2]:.1f} min | 3 lanes: {lane_waits_15m[3]:.1f} min")

    return {
        "source":             source,
        "prophet_preds":      prophet_preds,
        "prophet_vals":       prophet_vals,
        "lstm_vals":          lstm_vals,
        "xgb_vals":           xgb_vals,
        "ensemble_vals":      ensemble_vals,
        "checkout_arrivals":  checkout_arrivals,
        "wait_estimates":     wait_estimates,
        "wait_15m":           wait_15m,
        "wait_30m":           wait_30m,
        "wait_45m":           wait_45m,
        "lane_waits_15m":     lane_waits_15m,
        "current_queue":      current_queue,
        "avg_dwell_min":      avg_dwell_min,
        "per_bucket_dwell":   per_bucket_dwell,
        "active_lanes":       active_lanes,
        "service_per_bucket": service_per_bucket,
        "real_span_days":     real_span_days,
        "browsing_gap_min":   BROWSING_GAP_MIN,
    }


def _print_results(result: dict) -> None:
    prophet_preds      = result["prophet_preds"]
    prophet_vals       = result["prophet_vals"]
    lstm_vals          = result["lstm_vals"]
    xgb_vals           = result["xgb_vals"]
    ensemble_vals      = result["ensemble_vals"]
    checkout_arrivals  = result["checkout_arrivals"]
    wait_estimates     = result["wait_estimates"]
    service_per_bucket = result["service_per_bucket"]
    active_lanes       = result["active_lanes"]
    browsing_gap_min   = result["browsing_gap_min"]

    print("\n" + "=" * 85)
    print("  ENSEMBLE PREDICTED CUSTOMER ENTRIES — NEXT 60 MINUTES")
    print("=" * 85)
    print(f"  {'Time':<10} {'Prophet':>10} {'LSTM':>10} {'XGBoost':>10} {'Ensemble':>10} {'→Checkout':>12}")
    print("-" * 85)
    for i, row in prophet_preds.iterrows():
        print(
            f"  {row['ds'].strftime('%H:%M'):<10}"
            f" {prophet_vals[i]:>10.1f}"
            f" {lstm_vals[i]:>10.1f}"
            f" {xgb_vals[i]:>10.1f}"
            f" {ensemble_vals[i]:>10.1f}"
            f" {checkout_arrivals[i]:>12.1f}"
        )
    print("=" * 85)
    print(f"  (→Checkout = entrance shifted {browsing_gap_min} min forward for browsing gap)")

    print("\n" + "=" * 75)
    print("  QUEUE WAIT TIME ESTIMATES  (checkout arrivals + queue model)")
    print(f"  Service rate: {service_per_bucket:.1f} customers/{BUCKET_MINUTES}min  |  Lanes: {active_lanes}")
    print("=" * 75)
    print(f"  {'Time':<10} {'Checkout':>10} {'Est. Wait':>12}   Status")
    print("-" * 75)
    for i, row in prophet_preds.iterrows():
        wait   = wait_estimates[i]
        status = "OK" if wait < 5 else "BUSY" if wait < 10 else "ALERT"
        print(f"  {row['ds'].strftime('%H:%M'):<10} {checkout_arrivals[i]:>10.1f} {wait:>8} min   {status}")
    print("=" * 75)
    print(f"\n  Wait @ +15 min: {result['wait_15m']} min  |  Wait @ +30 min: {result['wait_30m']} min")


def _save_to_db(result: dict) -> None:
    prophet_preds  = result["prophet_preds"]
    prophet_vals   = result["prophet_vals"]
    lstm_vals      = result["lstm_vals"]
    xgb_vals       = result["xgb_vals"]
    ensemble_vals  = result["ensemble_vals"]
    wait_estimates = result["wait_estimates"]

    print("\n[DB] Saving predictions to queue_predictions...")
    conn = _connect()
    cur  = conn.cursor()

    cur.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")
    cur.execute("""
        CREATE TABLE IF NOT EXISTS queue_predictions (
            id                BIGSERIAL,
            predicted_at      TIMESTAMPTZ NOT NULL,
            prediction_for    TIMESTAMPTZ NOT NULL,
            prophet_yhat      NUMERIC(8,2),
            lstm_yhat         NUMERIC(8,2),
            xgb_yhat          NUMERIC(8,2),
            ensemble_yhat     NUMERIC(8,2),
            est_wait_minutes  NUMERIC(8,2),
            wait_15m          NUMERIC(8,2),
            wait_30m          NUMERIC(8,2),
            status            VARCHAR(10)
        )
    """)
    cur.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'queue_predictions'
                AND column_name = 'predicted_at'
                AND data_type = 'timestamp without time zone'
            ) THEN
                ALTER TABLE queue_predictions
                    ALTER COLUMN predicted_at   TYPE TIMESTAMPTZ USING predicted_at   AT TIME ZONE 'UTC',
                    ALTER COLUMN prediction_for TYPE TIMESTAMPTZ USING prediction_for AT TIME ZONE 'UTC';
            END IF;
        END $$;
    """)
    cur.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'queue_predictions' AND column_name = 'wait_15m'
            ) THEN
                ALTER TABLE queue_predictions
                    ADD COLUMN wait_15m NUMERIC(8,2),
                    ADD COLUMN wait_30m NUMERIC(8,2);
            END IF;
        END $$;
    """)
    cur.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'queue_predictions' AND column_name = 'wait_45m'
            ) THEN
                ALTER TABLE queue_predictions
                    ADD COLUMN wait_45m        NUMERIC(8,2),
                    ADD COLUMN wait_1lane_15m  NUMERIC(8,2),
                    ADD COLUMN wait_2lane_15m  NUMERIC(8,2),
                    ADD COLUMN wait_3lane_15m  NUMERIC(8,2);
            END IF;
        END $$;
    """)
    cur.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'queue_predictions' AND column_name = 'source'
            ) THEN
                ALTER TABLE queue_predictions
                    ADD COLUMN source VARCHAR(20) DEFAULT 'ensemble';
            END IF;
        END $$;
    """)
    cur.execute("""
        SELECT create_hypertable('queue_predictions', 'prediction_for',
            if_not_exists => TRUE, migrate_data => TRUE);
    """)
    cur.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'queue_predictions_prediction_for_key'
            ) THEN
                ALTER TABLE queue_predictions
                    ADD CONSTRAINT queue_predictions_prediction_for_key
                    UNIQUE (prediction_for);
            END IF;
        END $$;
    """)

    def _db_val(v):
        """Convert NaN/inf to None so PostgreSQL stores NULL instead of raising."""
        try:
            f = float(v)
            return None if (f != f or f == float("inf") or f == float("-inf")) else round(f, 2)
        except (TypeError, ValueError):
            return None

    _local_tz = datetime.now().astimezone().tzinfo

    def _local_wall_to_utc_dt(value) -> datetime | None:
        if value is None:
            return None
        ts = pd.Timestamp(value)
        if ts.tzinfo is None:
            ts = ts.tz_localize(_local_tz)
        else:
            ts = ts.tz_convert(_local_tz)
        return ts.tz_convert("UTC").to_pydatetime()

    predicted_at  = datetime.now(timezone.utc)
    lw            = result["lane_waits_15m"]
    _lw1          = _db_val(lw.get(1, 0.0))
    _lw2          = _db_val(lw.get(2, 0.0))
    _lw3          = _db_val(lw.get(3, 0.0))

    _steps_15 = 15 // BUCKET_MINUTES
    _steps_30 = 30 // BUCKET_MINUTES
    _steps_45 = 45 // BUCKET_MINUTES
    _we: list[float] = [float(v) for v in wait_estimates]  # type: ignore[union-attr]
    _n  = len(_we)
    _rows_saved = 0

    for i, row in prophet_preds.iterrows():
        wait   = round(_we[i], 2)
        status = "OK" if wait < 5 else "BUSY" if wait < 10 else "ALERT"
        _w15 = round(_we[i + _steps_15], 2) if i + _steps_15 < _n else None
        _w30 = round(_we[i + _steps_30], 2) if i + _steps_30 < _n else None
        _w45 = round(_we[i + _steps_45], 2) if i + _steps_45 < _n else None
        cur.execute("""
            INSERT INTO queue_predictions
                (predicted_at, prediction_for, prophet_yhat, lstm_yhat,
                 xgb_yhat, ensemble_yhat, est_wait_minutes,
                 wait_15m, wait_30m, wait_45m,
                 wait_1lane_15m, wait_2lane_15m, wait_3lane_15m, status, source)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (prediction_for) DO UPDATE SET
                predicted_at    = EXCLUDED.predicted_at,
                prophet_yhat    = EXCLUDED.prophet_yhat,
                lstm_yhat       = EXCLUDED.lstm_yhat,
                xgb_yhat        = EXCLUDED.xgb_yhat,
                ensemble_yhat   = EXCLUDED.ensemble_yhat,
                est_wait_minutes= EXCLUDED.est_wait_minutes,
                wait_15m        = EXCLUDED.wait_15m,
                wait_30m        = EXCLUDED.wait_30m,
                wait_45m        = EXCLUDED.wait_45m,
                wait_1lane_15m  = EXCLUDED.wait_1lane_15m,
                wait_2lane_15m  = EXCLUDED.wait_2lane_15m,
                wait_3lane_15m  = EXCLUDED.wait_3lane_15m,
                status          = EXCLUDED.status,
                source          = EXCLUDED.source
        """, (
            predicted_at,
            _local_wall_to_utc_dt(row["ds"]),
            _db_val(prophet_vals[i]),
            _db_val(lstm_vals[i]),
            _db_val(xgb_vals[i]),
            _db_val(ensemble_vals[i]),
            wait,
            _w15, _w30, _w45,
            _lw1, _lw2, _lw3,
            status,
            'ensemble',
        ))
        _rows_saved += 1

    conn.commit()
    cur.close()
    conn.close()
    print(f"[DB] Saved {_rows_saved} rows to queue_predictions [ok]")


if __name__ == "__main__":
    import argparse
    import traceback

    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=str, default="REAL", choices=["REAL", "SIM", "ALL"])
    parser.add_argument("--bootstrap", action="store_true",
                        help="Pad sparse real data with synthetic history when < 14 days available.")
    parser.add_argument("--days", type=int, default=DATA_SPAN_DAYS_DEFAULT,
                        help="Number of past days of entrance_events to use for training (default: DATA_SPAN_DAYS env var or 30).")
    args = parser.parse_args()

    _main_started = datetime.now()
    try:
        result = run_ensemble_forecast(source=args.source, bootstrap=args.bootstrap, data_span_days=args.days)
        _print_results(result)
        _save_to_db(result)
        _elapsed = (datetime.now() - _main_started).total_seconds()
        _log(f"\n[Run] Ensemble forecast finished successfully in {_elapsed:.1f}s")
    except Exception as exc:
        _elapsed = (datetime.now() - _main_started).total_seconds()
        _log(f"\n[Run] Ensemble forecast FAILED after {_elapsed:.1f}s: {exc}")
        traceback.print_exc()
        raise
