"""
push_alert_checker.py

Periodically checks every saved push subscription's own threshold/horizon
against the latest forecast, and sends a Web Push notification the moment
that specific subscription's value crosses into alert -- mirroring exactly
the rising-edge rule the frontend's own in-page alert already follows
(fire once on crossing, not on every poll), just running server-side so it
still works with no tab open and no browser running.

Each subscription carries its OWN threshold_min + horizon_min (sent by the
frontend when it subscribes -- see /push-subscribe in api.py), so a push
alert can never disagree with what that specific device's own in-page
alert would show. was_over is tracked per subscription in the database,
the same way wasAlertOverRef works in LiveScreen.jsx.

Requires pywebpush (pip install pywebpush) and a VAPID keypair -- see
VAPID_SETUP.md for how to generate one.

Usage:
    python push_alert_checker.py
    python push_alert_checker.py --interval 30
"""
from __future__ import annotations

import argparse
import json
import os
import time
from datetime import datetime

import psycopg2
import psycopg2.extras
from dotenv import find_dotenv, load_dotenv
from pywebpush import webpush, WebPushException

load_dotenv(find_dotenv(usecwd=True))

DB_CONFIG = dict(
    host=os.getenv("DB_HOST", "localhost"),
    port=int(os.getenv("DB_PORT", 5432)),
    dbname=os.getenv("DB_NAME", "iqms"),
    user=os.getenv("DB_USER", "postgres"),
    password=os.getenv("DB_PASSWORD", "0000"),
)
STORE_TZ = os.getenv("STORE_TZ", "Europe/Paris")

# Path to the PEM file generated by `vapid --gen` -- never the raw private
# key material itself in an env var, so it's never one copy-paste away
# from ending up somewhere it shouldn't (shell history, a screenshot, etc).
VAPID_PRIVATE_KEY_PATH = os.getenv("VAPID_PRIVATE_KEY_PATH")
# Required by the Web Push spec -- a contact the push service can reach if
# this server is ever sending excessive/abusive traffic. Must be a real
# address, not a placeholder, once this is actually in use.
VAPID_CONTACT_EMAIL = os.getenv("VAPID_CONTACT_EMAIL", "mailto:admin@example.com")


def _now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _conn():
    conn = psycopg2.connect(**DB_CONFIG)
    with conn.cursor() as cur:
        cur.execute("SET timezone = %s", (STORE_TZ,))
    conn.commit()
    return conn


def _wait_for_horizon(cur, horizon_min: int) -> "float | None":
    """
    Mirrors /forecast (for 0/5/10/15) and /forecast/wait (for anything
    else) in api.py exactly, so a push alert can never disagree with what
    the app itself would show for the same horizon.
    """
    if horizon_min in (0, 5, 10, 15):
        cur.execute("SELECT wait_0m, wait_5m, wait_10m, wait_15m FROM dashboard_state WHERE id = 1")
        row = cur.fetchone()
        if not row:
            return None
        col = {0: "wait_0m", 5: "wait_5m", 10: "wait_10m", 15: "wait_15m"}[horizon_min]
        value = row[col]
        return float(value) if value is not None else None

    cur.execute("SELECT MAX(predicted_at) AS latest FROM queue_predictions")
    latest = (cur.fetchone() or {}).get("latest")
    if latest is None:
        return None
    cur.execute("""
        SELECT est_wait_minutes
        FROM queue_predictions
        WHERE predicted_at = %s
        ORDER BY ABS(EXTRACT(EPOCH FROM (
            prediction_for - (NOW() + (%s || ' minutes')::interval)
        )))
        LIMIT 1
    """, (latest, horizon_min))
    row = cur.fetchone()
    if not row or row["est_wait_minutes"] is None:
        return None
    return float(row["est_wait_minutes"])


def _send_push(sub) -> str:
    """Returns 'ok', 'gone' (subscription expired/revoked -- caller should
    delete it), or 'error' (transient failure -- caller should keep it and
    just retry next cycle)."""
    message = (
        f"Wait predicted at {round(sub['_wait_value'], 1)} min "
        f"in {sub['horizon_min']} min (threshold: {sub['threshold_min']} min)."
        if sub["horizon_min"] > 0 else
        f"Current wait at {round(sub['_wait_value'], 1)} min "
        f"(threshold: {sub['threshold_min']} min)."
    )
    payload = json.dumps({"title": "IQMS", "body": message, "url": "/"})
    try:
        webpush(
            subscription_info={
                "endpoint": sub["endpoint"],
                "keys": {"p256dh": sub["p256dh"], "auth": sub["auth"]},
            },
            data=payload,
            vapid_private_key=VAPID_PRIVATE_KEY_PATH,
            vapid_claims={"sub": VAPID_CONTACT_EMAIL},
        )
        return "ok"
    except WebPushException as exc:
        status = getattr(exc.response, "status_code", None)
        if status in (404, 410):
            return "gone"
        print(f"[{_now()}] Push error for {sub['endpoint'][:60]}...: {exc}")
        return "error"


def check_once():
    with _conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("SELECT * FROM push_subscriptions")
            subs = cur.fetchall()

            sent, cleared, removed = 0, 0, 0
            for sub in subs:
                wait_value = _wait_for_horizon(cur, sub["horizon_min"])
                if wait_value is None:
                    continue
                is_over = wait_value >= sub["threshold_min"]

                if is_over and not sub["was_over"]:
                    sub["_wait_value"] = wait_value
                    result = _send_push(sub)
                    if result == "gone":
                        cur.execute("DELETE FROM push_subscriptions WHERE endpoint = %s", (sub["endpoint"],))
                        removed += 1
                        continue
                    if result == "ok":
                        sent += 1
                    cur.execute(
                        "UPDATE push_subscriptions SET was_over = TRUE, updated_at = NOW() WHERE endpoint = %s",
                        (sub["endpoint"],),
                    )
                elif not is_over and sub["was_over"]:
                    cur.execute(
                        "UPDATE push_subscriptions SET was_over = FALSE, updated_at = NOW() WHERE endpoint = %s",
                        (sub["endpoint"],),
                    )
                    cleared += 1
        conn.commit()

    if subs:
        print(f"[{_now()}] Checked {len(subs)} subscription(s) | sent={sent} cleared={cleared} removed_expired={removed}")


def main():
    parser = argparse.ArgumentParser(description="Check push subscriptions against live forecast, send Web Push on crossing.")
    parser.add_argument("--interval", type=int, default=int(os.getenv("PUSH_CHECK_INTERVAL_SEC", 30)),
                        help="Seconds between checks (default: 30)")
    args = parser.parse_args()

    if not VAPID_PRIVATE_KEY_PATH:
        print("[push_alert_checker] ERROR: VAPID_PRIVATE_KEY_PATH is not set. See VAPID_SETUP.md.")
        return

    print(f"[Scheduler] Starting push alert checker -- every {args.interval}s")
    print("[Scheduler] Press Ctrl+C to stop.\n")

    while True:
        try:
            check_once()
        except Exception as exc:
            print(f"[{_now()}] check_once() failed: {exc}")
        time.sleep(args.interval)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n[{_now()}] Push alert checker stopped.")
