camID: Bosch_Camera_exit
ip_address: '192.168.1.48:554/?inst=2'
username: service
password: 'Cam10003!'

custom_model: models/yolov9_s_discrete_headpose_post_0100_1x3x480x640.onnx
disable_headpose_identification_mode: True

score: 0.15
min_delay: 0.45

rois:
  - name: lane1
    points:
      - - 2
        - 2
      - - 187
        - 5
      - - 86
        - 261
      - - 1
        - 188  
  - name: lane2
    points:
    - - 130
      - 407
    - - 244
      - 17
    - - 309
      - 17
    - - 350
      - 407
  - name: lane3
    points:
    - - 345
      - 4
    - - 480
      - 446
    - - 567
      - 101
    - - 458
      - 7
  - name: lane4
    points:
    - - 570
      - 117
    - - 461
      - 1
    - - 526
      - 2
    - - 582
      - 66  
